backend:
  name: git-gateway
  branch: master
  repo: SimonBachmaier/reittherapie

media_folder: static/img
public_folder: /img

collections:
  - name: "news"
    identifier_field: "siteTitle"
    label: "Interessantes"
    folder: "src/pages/aktuelles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news"}
      - {label: "Seitentitel", name: "siteTitle", widget: "string"}
      - {label: "Header-Bild", name: "headerImage", widget: "image"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Titel neben Bild", name: "headline", widget: "string"}
      - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
      - {label: "Beschreibung neben Bild", name: "body", widget: "markdown"}

  - name: "horse"
    identifier_field: "name"
    label: "Pferde"
    folder: "src/pages/pferde"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "horse"}
      - {label: "Seitentitel", name: "siteTitle", widget: "string"}
      - {label: "Reihenfolge in Navigation (kleinste Zahl zuerst)", name: "navigationOrder", widget: "number"}
      - {label: "Header-Bild", name: "headerImage", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Kurzbeschreibung", name: "description", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Titel neben Bild", name: "headline", widget: "string"}
      - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
      - {label: "Beschreibung neben Bild", name: "body", widget: "markdown"}

  - name: "feature"
    identifier_field: "name"
    label: "Therapien"
    folder: "src/pages/leistungen"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "horse"}
      - {label: "Seitentitel", name: "siteTitle", widget: "string"}
      - {label: "Reihenfolge in Navigation (kleinste Zahl zuerst)", name: "navigationOrder", widget: "number"}
      # - {label: "Kurzbeschreibung in den Boxen (z.B. auf der Startseite)", name: "description", widget: "string"}
      - {label: "Vorschaubild in den Boxen (z.B. auf der Startseite)", name: "previewImage", widget: "image"}
      - {label: "Header-Bild", name: "headerImage", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Titel neben Bild", name: "headline", widget: "string"}
      - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
      - {label: "Beschreibung neben Bild", name: "textNextToImage", widget: "markdown"}
      - {label: "Fließtext", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/pages/index.md"
        label: "Startseite"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Header-Bild", name: "headerImage", widget: "image"}
          - {label: "Titel", name: headline, widget: string}
          - {label: "Untertitel", name: subheadline, widget: markdown}
          - {label: "Fließtext", name: "body", widget: "markdown"}
      - file: "src/pages/aktuelles.md"
        label: "Interessantes"
        name: "aktuelles"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Header-Bild", name: "headerImage", widget: "image"}
          - {label: "Beschreibung", name: "description", widget: "string"}
      - file: "src/pages/ueber-mich.md"
        label: "Über mich"
        name: "ueber-mich"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Header-Bild", name: "headerImage", widget: "image"}
          - {label: "Bild", name: "image", widget: "image"}
          - {label: "Titel neben Bild", name: "headline", widget: "string"}
          - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
          - {label: "Beschreibung neben Bild", name: "textNextToImage", widget: "markdown"}
          - {label: "Fließtext", name: "body", widget: "markdown"}
      - file: "src/pages/impressum.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "text"}
          - {label: "ID", name: "id", widget: "hidden"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Fließtext", name: "body", widget: "markdown"}
      - file: "src/pages/datenschutz.md"
        label: "Datenschutzerklärung"
        name: "datenschutz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "text"}
          - {label: "ID", name: "id", widget: "hidden"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Fließtext", name: "body", widget: "markdown"}
